import Link from "next/link";

export const metadata = {
  title: "Terms of Service – BiteSized",
  description: "Terms of Service for BiteSized. By using the service you agree to these terms.",
};

export default function TermsPage() {
  return (
    <div className="p-6 md:p-8 max-w-5xl mx-auto">
      <div className="mb-8">
        <p className="text-sm text-[var(--muted)] mb-1">
          <Link href="/" className="hover:text-[var(--foreground)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)] rounded">
            ← Dashboard
          </Link>
        </p>
        <h1 className="text-2xl font-semibold text-[var(--foreground)]">
          Terms of Service
        </h1>
        <p className="text-sm text-[var(--muted)] mt-1">
          Last updated: March 2, 2025
        </p>
      </div>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          1. Acceptance
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          By accessing or using BiteSized (“Service”), you agree to be bound by these Terms of Service (“Terms”) and our Privacy Policy. If you do not agree to these Terms or the Privacy Policy, do not use the Service.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          2. Description of service
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          BiteSized is a web application that turns user-provided content—including text, uploaded files, and URLs (articles and YouTube videos)—into study materials such as summaries, key points, flashcards, quiz questions, outlines, mind maps, and Q&A. The Service is provided “as is” and may be modified, suspended, or discontinued at any time.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          3. Eligibility
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          The Service is offered globally. You must be old enough to form a binding contract in your jurisdiction (e.g., 18 or older, or 13 or older with parental consent where applicable). You may not use the Service where prohibited by local law. You represent that you are not located in a country subject to embargo or designated as supporting terrorism, and that you will not use the Service in violation of export or sanctions laws. We may restrict or block access from certain jurisdictions where required by law.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          4. Acceptable use
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          You agree not to: use the Service for any illegal purpose; upload or submit content you do not have the right to use; attempt to reverse-engineer, disrupt, or overload the Service; use automated access (e.g., scraping or bots) unless expressly permitted; or violate any applicable laws in your country. We reserve the right to suspend or terminate your access at any time for violation of these Terms or for any other reason.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          5. User content and license
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          You retain ownership of content you submit. You grant BiteSized a limited, royalty-free license to use, process, and transmit that content solely to provide and improve the Service, including sending it to third-party AI and data processors as described in our Privacy Policy.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          6. AI-generated output
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          Study materials are generated by automated systems. They are for educational and personal use only. We do not guarantee their accuracy, completeness, or suitability for any purpose. They are not professional, medical, legal, or financial advice. You rely on them at your own risk.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          7. Intellectual property
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          BiteSized and its licensors own the Service, its design, and branding. You receive a limited license to use the Service and to use generated output for your personal, non-commercial use.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          8. Disclaimers
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          9. Limitation of liability
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          TO THE MAXIMUM EXTENT PERMITTED BY LAW: (A) BITESIZED AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES; (B) OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM, OR $100 USD IF YOU PAID NOTHING. SOME JURISDICTIONS DO NOT ALLOW THESE LIMITATIONS; WHERE PROHIBITED, OUR LIABILITY IS LIMITED TO THE MINIMUM PERMITTED BY LAW.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          10. Indemnification
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          You agree to indemnify and hold harmless BiteSized and its operators from any claims, damages, losses, and costs (including reasonable attorneys’ fees) arising from your use of the Service, your content, or your breach of these Terms.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          11. Termination
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          We may suspend or terminate your access at any time. You may stop using the Service at any time. Provisions that by their nature should survive (including disclaimers, limitation of liability, indemnification, and governing law) will survive termination.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          12. Governing law and disputes
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Where mandatory local law (e.g., consumer rights in the EU or UK) gives you rights that cannot be waived by contract, that local law applies to the extent required. Any dispute shall be resolved in the courts or by arbitration in the operator’s jurisdiction. To the extent enforceable in your jurisdiction, you agree to resolve disputes by binding individual arbitration (e.g., JAMS or AAA rules) and waive the right to participate in class actions; small-claims court and opt-out procedures may apply as required by law.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          13. Changes to terms
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          We may change these Terms. We will post the updated Terms and update the “Last updated” date. Your continued use of the Service after the effective date constitutes acceptance. For material changes we may provide additional notice (e.g., in-app or by email if we have it).
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          14. Severability
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          If any provision of these Terms is held invalid or unenforceable, the remaining provisions remain in full force and effect.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          15. Entire agreement
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          These Terms and the Privacy Policy constitute the entire agreement between you and BiteSized regarding the Service.
        </p>
      </section>

      <section className="space-y-4 mb-8">
        <h2 className="text-xs font-medium uppercase tracking-wider text-[var(--muted)]">
          16. Contact
        </h2>
        <p className="text-sm leading-relaxed text-[var(--foreground)]">
          For questions about these Terms, contact BiteSized via the Contact link in the footer or at the contact address provided on the Service.
        </p>
      </section>

      <footer className="mt-12 pt-8 border-t border-[var(--card-border)] text-center text-sm text-[var(--muted)] no-print">
        BiteSized · <Link href="/about" className="hover:text-[var(--foreground)]">About</Link> · <Link href="/terms" className="hover:text-[var(--foreground)]">Terms</Link> · <Link href="/privacy" className="hover:text-[var(--foreground)]">Privacy</Link> · <a href="#" className="hover:text-[var(--foreground)]">Contact</a>
      </footer>
    </div>
  );
}
